title       = "okx"
baseURL     = "https://okx-cli.tamnd.com/"
description = "A command line for OKX crypto exchange market data."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/okx-cli"
